[project]
name = "Tworzenie prostej aplikacji internetowej w Flask"
authors = [{name = "Wiktor Pieprzowski", index = "156657"}]
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "requests",
    "Flask"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "coverage"
]
